# KBGAT Source Code

# main.py

## Hàm `def load_data(args):`

### 1. build_data( args.data, is_unweigted=False, directed=True)

##### `train_data` : `(train_triples, train_adjacency_mat)` :

Trong đó : 

`train_triples` : `(entity2id[e1], relation2id[relation], entity2id[e2])`

`train_adjacency_mat` : `(rows, cols, data)`


`validation_data`, `test_data` : tương tự `train_data`

`entity2id`

`relation2id`

`headTailSelector` : 

`unique_entities_train`


`entity_embeddings` : shape = [len(entity2id) : args.embedding_size]

Có kích thước là [số lượng entity, số chiều k]

## Hàm def train_gat(args):

Định nghĩa mô hình 

#### SpKBGATModified()

`entity_embeddings`

`relation_embeddings`

`args.entity_out_dim`

`args.entity_out_dim`

`args.drop_GAT`

`args.alpha`

`args.nheads_GAT`

## Class SpKBGATModified:

`num_nodes`
`entity_in_dim`
`entity_out_dim_1`
`nheads_GAT_1`
`entity_out_dim_2`
`nheads_GAT_2`

#### Properties of Relations

`num_relation`
`relation_dim`
`relation_out_dim_1`
`drop_GAT`
`alpha`

#### Parameter
40943 : số phần tử entity trong tập train

11 : số phần tử relation trong tập train

[100, 200] : Entity output embedding dimensions (entity_out_dim)

[2, 2] : Multihead attention SpGAT (nheads_GAT)

50 : số chiều nhúng k ban đầu
```
final_entity_embeddings : torch.Size([40943, 200])
final_relation_embeddings : torch.Size([11, 200])
entity_embeddings : torch.Size([40943, 50])
relation_embeddings : torch.Size([11, 50])
W_entities : torch.Size([50, 200])
sparse_gat_1.W : torch.Size([50, 200])
sparse_gat_1.attention_0.a : torch.Size([100, 150])
sparse_gat_1.attention_0.a_2 : torch.Size([1, 100])
sparse_gat_1.attention_1.a : torch.Size([100, 150])
sparse_gat_1.attention_1.a_2 : torch.Size([1, 100])
sparse_gat_1.out_att.a : torch.Size([200, 600])
sparse_gat_1.out_att.a_2 : torch.Size([1, 200])
```


* `final_entity_embeddings` : shape = [num_nodes, entity_out_dim_1 * nheads_GAT_1]

(Kết quả nhúng thực thể : [số lượng nodes, kích thước output entity * số nheads_GAT_1])

* `final_relation_embeddings`: shape = [num_relation, entity_out_dim_1 * nheads_GAT_1]

* `entity_embeddings` : `initial_entity_emb`

* `relation_embeddings` : `initial_relation_emb`

* sparse_gat_1: SpGAT : tập hợp các paramter của lớp SpGAT

* `W_entities` : trọng số thực thể với shape = [entity_in_dim, entity_out_dim_1 * nheads_GAT_1]

## class SpGAT(nn.Module)
```python
SpKBGATModified(
  (sparse_gat_1): SpGAT(
    (dropout_layer): Dropout(p=0.3, inplace=False)
    (attention_0): SpGraphAttentionLayer (50 -> 100)
    (attention_1): SpGraphAttentionLayer (50 -> 100)
    (out_att): SpGraphAttentionLayer (200 -> 200)
  )
)
```


```python
sparse_gat_1.W : torch.Size([50, 200])
sparse_gat_1.attention_0.a : torch.Size([100, 150])
sparse_gat_1.attention_0.a_2 : torch.Size([1, 100])
sparse_gat_1.attention_1.a : torch.Size([100, 150])
sparse_gat_1.attention_1.a_2 : torch.Size([1, 100])
sparse_gat_1.out_att.a : torch.Size([200, 600])
sparse_gat_1.out_att.a_2 : torch.Size([1, 200])```


#### Dropout

`dropout_layer = nn.Dropout(self.dropout)`

torch.Size([40943, 200])

## Hàm def forward() trong layer SpGAT

Input : 
```
Corpus_
batch_inputs
entity_embeddings
relation_embed
edge_list
edge_type
edge_embed
edge_list_nhop
edge_type_nhop
```


## Hàm def forward() trong layer chính (SpKBGATModified)
Input :

`train_adj_matrix` : gồm hai phần tử `(adj_indices, adj_values)`
`train_indices` : lấy từ hàm `get_iteration_batch` : `batch_indices` : là index lấy ra của từng batch
`current_batch_2hop_indices` : Lấy 2 hop indices kế cận của batch


`edge_list` : head
`edge_type` : tailSpectrum of a bounded operator

input, edge, edge_embed, edge_list_nhop, edge_embed_nhop):




### model_conv
```python
final_entity_embeddings : torch.Size([40943, 200])
final_relation_embeddings : torch.Size([11, 200])
convKB.conv_layer.weight : torch.Size([500, 1, 1, 3])
convKB.conv_layer.bias : torch.Size([500])
convKB.fc_layer.weight : torch.Size([1, 100000])
convKB.fc_layer.bias : torch.Size([1])

```

```python
SpKBGATConvOnly(
  (convKB): ConvKB(
    (conv_layer): Conv2d(1, 500, kernel_size=(1, 3), stride=(1, 1))
    (dropout): Dropout(p=0.0, inplace=False)
    (non_linearity): ReLU()
    (fc_layer): Linear(in_features=100000, out_features=1, bias=True)
  )
)
```

# Debug

```python
entity_embeddings (40943, 50)
relation_embed(11, 50)


edge_list[i] (2, 86835) : head_id, tail_id của một cạnh i ()
edge_type[i] (86835) : relation_id của một cạnh i

edge_list_nhop[i] (2, 207376) : neigh_entity_id1, neigh_entity_id2 của một cạnh hàng xóm với source
edge_type[i] (2, 207376) : neigh_relation_id_1, neigh_relation_id_1

edge_embed (86835, 50)


edge_embed_nhop (207376, 50) = G_nhop1 + G_nhop2

train_indices_nhop (207376, 4)

N = 40943

___________________________________________
edge (2, 294211)
edge_embed (2, 294211) = edge_embed(86835, 50) + edge_embed_nhop(207376, 50)

edge_h (150, 294211)

A_1 (100, 150)
edge_m (100, 294211)


A_2 (1, 100)

powers (294211)
edge_e (294211, 1)



```

In [2]:
import torch
import torch.nn as nn
m = nn.Dropout(p=0.2)
input = torch.randn(20, 16)
output = m(input)

tensor([[-1.9777, -0.7239, -0.0000, -0.4364, -0.6596, -0.4482, -1.3001, -0.0000,
          0.0000, -0.4294, -0.0499,  0.0000, -0.0000,  1.7630,  0.7044, -1.3654],
        [ 0.2236,  1.5024, -1.7158,  1.4000, -0.5982,  0.6613,  0.0116,  0.0303,
         -1.0553,  0.0000,  0.0000, -0.6678,  1.7476, -0.0000, -2.8633, -0.0915],
        [-2.3893,  0.0000,  0.9400,  0.5557,  0.1895, -0.4985,  2.2090, -2.2435,
         -0.9534,  2.0380,  0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0376, -2.3209, -0.5383,  0.0000, -1.7053,  0.0805,  0.3283,
         -1.4172,  0.0000,  0.9477,  0.1731, -0.0000, -1.8240, -0.0000, -0.3835],
        [-1.1860,  0.0000,  0.8988,  1.2359, -1.4951, -0.4405,  0.2935, -0.4562,
          0.4369,  2.7884,  0.3049, -3.0162, -0.0000,  1.4591,  1.3809,  0.4325],
        [ 1.0054,  0.7971, -0.5789,  0.7449, -0.6467,  1.2005, -2.6526,  0.1047,
         -3.5634, -0.8093,  0.3248,  2.9277,  0.1632,  2.3533, -1.6232,  0.0660],
        [ 1.5035,  0.0

In [4]:
import torch

In [43]:
a = torch.tensor([[10,8], [4,8], [5,6]])

In [44]:
a.size()

torch.Size([3, 2])

In [45]:
b = torch.tensor([[1],[2],[9]])

In [46]:
b.size()

torch.Size([3, 1])

In [47]:
c = a.div(b)

In [48]:
c

tensor([[10,  8],
        [ 2,  4],
        [ 0,  0]])

In [31]:
c.size()

torch.Size([3, 2])

In [2]:
import torch
output = torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long))
output

tensor([1, 2, 3])

In [13]:
t = torch.arange(12).reshape(4,3)
t

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [17]:
b = t.view(-1)
b

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b

tensor([[0.9011, 0.6054, 0.0080, 0.4059, 0.5573, 0.8005, 0.4834, 0.1177],
        [0.3184, 0.5011, 0.2572, 0.6653, 0.0610, 0.2073, 0.0534, 0.4135]])